//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoopSystemWebApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class employment
    {
        public int id { get; set; }
        public string position { get; set; }
        public System.DateTime date_hired { get; set; }
        public string employer { get; set; }
        public string employer_address { get; set; }
        public string contact_numbers { get; set; }
        public string monthly_income { get; set; }
        public int member_id { get; set; }
    
        public virtual member member { get; set; }
    }
}
