//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoopSystemWebApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class group_options
    {
        public long id { get; set; }
        public long registered_group_id { get; set; }
        public long option_id { get; set; }
        public decimal amount { get; set; }
        public long member_id { get; set; }
    
        public virtual member_info member_info { get; set; }
        public virtual option option { get; set; }
        public virtual registered_group registered_group { get; set; }
    }
}
