//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoopSystemWebApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class loan_application
    {
        public int id { get; set; }
        public int member_id { get; set; }
        public string terms_of_payment { get; set; }
        public int loan_type_id { get; set; }
        public System.DateTime date_created { get; set; }
        public Nullable<System.DateTime> from_date { get; set; }
        public Nullable<System.DateTime> to_date { get; set; }
    
        public virtual loan_type loan_type { get; set; }
        public virtual member member { get; set; }
    }
}
