//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoopSystemWebApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class member_info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public member_info()
        {
            this.group_options = new HashSet<group_options>();
        }
    
        public long id { get; set; }
        public string last_name { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public System.DateTime dob { get; set; }
        public string random_id_number { get; set; }
        public long status_id { get; set; }
        public long created_by { get; set; }
        public long registered_group_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<group_options> group_options { get; set; }
        public virtual user_account user_account { get; set; }
        public virtual registered_group registered_group { get; set; }
        public virtual status status { get; set; }
    }
}
