//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoopSystemWebApp.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class nasccoEntities : DbContext
    {
        public nasccoEntities()
            : base("name=nasccoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<employment> employments { get; set; }
        public virtual DbSet<fees_category> fees_category { get; set; }
        public virtual DbSet<fees_masterfile> fees_masterfile { get; set; }
        public virtual DbSet<loan_application> loan_application { get; set; }
        public virtual DbSet<loan_type> loan_type { get; set; }
        public virtual DbSet<payment> payments { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<setting> settings { get; set; }
        public virtual DbSet<status> statuses { get; set; }
        public virtual DbSet<member> members { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<spouse> spouses { get; set; }
        public virtual DbSet<reference> references { get; set; }
    }
}
