//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoopSystemWebApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class reference
    {
        public int id { get; set; }
        public string full_name { get; set; }
        public string address { get; set; }
        public string contact_number { get; set; }
        public string relation { get; set; }
        public int member_id { get; set; }
    
        public virtual member member { get; set; }
    }
}
