//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoopSystemWebApp.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class insurancedbEntities : DbContext
    {
        public insurancedbEntities()
            : base("name=insurancedbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<card_processor> card_processor { get; set; }
        public virtual DbSet<commercial> commercials { get; set; }
        public virtual DbSet<coverage> coverages { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<group_options> group_options { get; set; }
        public virtual DbSet<member_info> member_info { get; set; }
        public virtual DbSet<option> options { get; set; }
        public virtual DbSet<option_limit> option_limit { get; set; }
        public virtual DbSet<registered_group> registered_group { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<status> status { get; set; }
        public virtual DbSet<transaction> transactions { get; set; }
        public virtual DbSet<transaction_type> transaction_type { get; set; }
        public virtual DbSet<user_account> user_account { get; set; }
    }
}
