//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoopSystemWebApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class setting
    {
        public int id { get; set; }
        public string description { get; set; }
        public decimal value { get; set; }
        public Nullable<int> fees_masterfile_id { get; set; }
        public string tags { get; set; }
    
        public virtual fees_masterfile fees_masterfile { get; set; }
    }
}
