//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoopSystemWebApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class spouse
    {
        public int id { get; set; }
        public string lastname { get; set; }
        public string firstname { get; set; }
        public string middlename { get; set; }
        public System.DateTime date_of_birth { get; set; }
        public string occupation { get; set; }
        public string employer { get; set; }
        public string employer_address { get; set; }
        public string employer_contact { get; set; }
        public Nullable<decimal> monthly_income { get; set; }
        public string contact_numbers { get; set; }
        public int employment_status { get; set; }
        public Nullable<System.DateTime> date_started { get; set; }
        public Nullable<System.DateTime> date_ended { get; set; }
        public int member_id { get; set; }
        public int created_by_user_id { get; set; }
    
        public virtual member member { get; set; }
        public virtual user user { get; set; }
        public virtual status status { get; set; }
    }
}
