//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoopSystemWebApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction
    {
        public long id { get; set; }
        public decimal amount { get; set; }
        public Nullable<decimal> discount { get; set; }
        public System.DateTime date_created { get; set; }
        public Nullable<System.DateTime> date_updated { get; set; }
        public long registered_group_id { get; set; }
        public long status_id { get; set; }
        public string card_number { get; set; }
        public string card_type { get; set; }
        public string card_last_four { get; set; }
        public long card_processor_id { get; set; }
        public string cvv { get; set; }
        public string gateway_transaction_id { get; set; }
        public long transaction_type_id { get; set; }
        public long created_by { get; set; }
        public string exp_year { get; set; }
        public string exp_month { get; set; }
        public string currency { get; set; }
    
        public virtual card_processor card_processor { get; set; }
        public virtual registered_group registered_group { get; set; }
        public virtual status status { get; set; }
        public virtual user_account user_account { get; set; }
        public virtual transaction_type transaction_type { get; set; }
    }
}
